zstd: disable C++14 [[deprecated]] atribute
Instead use the compiler-specific versions because of:

    ../contrib/zstd/lib/zstd.h:191:1: error: an attribute list cannot appear here
    ZSTD_DEPRECATED("Replaced by ZSTD_getFrameContentSize")
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../contrib/zstd/lib/zstd.h:49:38: note: expanded from macro 'ZSTD_DEPRECATED'
    #    define ZSTD_DEPRECATED(message) [[deprecated(message)]]
					 ^~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Signed-off-by: Steven Noonan <steven@uplinklabs.net>